data:
  DB_USER: Y3N5ZTcxMjU=
  DB_PASSWORD: Y3N5ZTcxMjVwYXNz
  NODE_ENV: webapp
  DB_NAME: rdsdbcsye7125


replicaCount: 3

progressDeadlineSecondsCount: 120

minReadySecondsCount: 30

namespace: "kubernetes-dashboard"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: "regcred"

image:
  name: todo
  repository: csye7125fall2022group07/todo-app:v9
  pullPolicy: Always

initContainer:
  args: migrate
  name: db-migration-flyway
  image: csye7125fall2022group07/db-migrate-flyway:v2

appContainer:
  containerPort: 3000


service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000

readinessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10


requests:
  memory: "100Mi"
  cpu: "500m"
limits:
  memory: "256Mi"
  cpu: "1000m"
