data:
  DB_USER: ""
  DB_PASSWORD: ""
  NODE_ENV: ""
  DB_NAME: ""
  FLYWAY_ENDPOINT: ""
  DB_HOST: ""
  elastic_endpoint: ""
  kafka_broker: ""
  kafka_topic: "todotask"

replicaCount: 3

progressDeadlineSecondsCount: 120

minReadySecondsCount: 30

namespace: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: ""

image:
  name: todo
  repository: ""
  pullPolicy: Always
  tag: fall2022-v1

initContainer:
  args: migrate
  name: db-migration-flyway
  image: "csye7125fall2022group07/db-migrate-flyway:v2"

appContainer:
  containerPort: 3030


service:
  type: LoadBalancer
  port: 3030
  targetPort: 3030

readinessProbe:
  httpGet:
    path: /healthz
    port: 3030
  initialDelaySeconds: 60
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /healthz
    port: 3030
  initialDelaySeconds: 60
  periodSeconds: 10


requests:
  memory: "100Mi"
  cpu: "500m"
limits:
  memory: "256Mi"
  cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5