---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.name" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "todo-app.name" .}}
data:
  DB_USER: {{ .Values.data.DB_USER }}
  DB_PASSWORD: {{ .Values.data.DB_PASSWORD }}
  # DB_USER: {{ .Values.data.DB_USER | b64enc | quote }}
  # DB_PASSWORD: {{ .Values.data.DB_PASSWORD | b64enc | quote }}