---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.name" .}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "todo-app.name" .}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "todo-app.name" .}}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}