name: Chart Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow
    
      - name: Lint Helm charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: helm lint
          arguments: -syntax-only
          target: ./helm-chart/todo-app
