name: Chart Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script file
        run: |
          pwd
          cd helm-chart
          helm lint .
          helm template .
